<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'acme_api.event.jwt_created_listener' shared autowired service.

include_once $this->targetDirs[3].'/src/EventListener/JWTCreatedListener.php';

return $this->privates['acme_api.event.jwt_created_listener'] = new \App\EventListener\JWTCreatedListener(($this->services['request_stack'] ?? $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()));
