# api/config/schema.yaml
# The list of types and properties we want to use
types:
    # Parent class of Person
    User:
        properties:
            lastName: ~
            surName: ~
            role: ~
            type: ~
            email: ~
            flat: ~
    Reservation:
        properties:
            user: ~
            room: ~
            startTime: ~
            endTime: ~
    Room:
        properties:
            name: ~
            description: ~
            instruction: ~