<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\GetUserNameDTO' shared autowired service.

include_once $this->targetDirs[3].'/src/Controller/GetUserNameDTO.php';

return $this->services['App\Controller\GetUserNameDTO'] = new \App\Controller\GetUserNameDTO(($this->privates['App\Repository\UserCustomRepository'] ?? $this->load('getUserCustomRepositoryService.php')));
