index:
    path: /
    controller: App\Controller\DefaultController::index

parse_excel:
    path: /api/parse_excel/{id}
    controller: App\Controller\ExcelController::parseExcel

api_login_check:
    path: /api/login
