<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYBAEcXN\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYBAEcXN/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYBAEcXN.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYBAEcXN\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerYBAEcXN\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'YBAEcXN',
    'container.build_id' => 'fdd09e5d',
    'container.build_time' => 1531350913,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerYBAEcXN');
